[package]
name = "domain_pure"
version = "0.1.0"
edition = "2021"

[dependencies]
crosscutting = { path = "../crosscutting" }
derive_builder = "0.20.0"
serde = { version = "1.0", features = ["derive"] }
mockall = { version = "0.12.1", optional = true }

[dev-dependencies]
mockall = "0.12.1"