=== Clone on Write (`Cow`)

The Clone on Write (`Cow`) strategy provides a flexible approach that defers cloning until it becomes necessary. If the data is not modified, `Cow` borrows it from the source object. If modifications are needed, `Cow` clones the data on demand. This decision can often be deferred until runtime  making `Cow` a powerful tool for optimization while maintaining flexibility.

.Code Snippet
[source,rust]
----
use std::borrow::Cow;

pub fn domain_to_dto<'a>(domain: &'a DomainModel) -> DtoModel<'a> {
    DtoModel {
        data: Cow::Borrowed(&domain.data)
    }
}
----
In this example, `DtoModel` bowrrows data from `DomainModel` initially. If later operations requires modifying the data `Cow` transparently handles cloning, transitioning from borrowed to owned date seamlessly. `<'a>` is a lifetime parameter telling the compiler, that the Returnvalue of the function will contain data borrowed from the `DomainModel`. It ensures that the 'DtoModel' can not outlive 'DomainModel' preventing invalid memory access.

another variant is, to use a feature called _lifetime elision_ and leave it to the compiler to determin the necessary lifetime parameter

.Code Snippet
[source,rust]
----
pub fn domain_to_dto_cow(domain: &DomainModel) -> DtoModelCow<'_> {
----

usage:

.Code Snippet
[source,rust]
----
let domain_model = DomainModel { data: "some data".into() };
let dto_cow = domain_to_dto_cow(&domain_model);

match dto_cow.data {
    Cow::Borrowed(borrowed) => println!("Borrowed data: {}", borrowed),
    Cow::Owned(owned) => println!("Owned data: {}", owned),
}
----


.Pros
- Offers a dynamic balance between efficiency and flexibility.
- Avoids cloning when the data is not modified, optimizing performance.

.Cons
- Introduces slight runtime overhead due to dynamic cloning decisions.
- Adds complexity through explicit lifetime annotations and management.