[workspace]
members = [
    "app-backend/adapter",
    "app-backend/port",
    "app-backend/application",
    "app-backend/domain_pure",
    "app-backend/entry_point",
    "app-backend/crosscutting"
]
resolver = "2"