@startuml
top to bottom direction

rectangle "backend" #DEDFE5 {

rectangle "crosscutting" #8387C4 {
    package "framework" #E2E3F5 {
        [Errors] #B7BBF2
    }
}

rectangle "domain pure" #8387C4 {

    package "model" #E2E3F5 {
        [location] #B7BBF2
        [passage] #B7BBF2
        [player_state] #B7BBF2
    }

    package "pure services" #E2E3F5 {
        [service 1] #B7BBF2
    }


}

rectangle "domain contract" #8387C4 {

    package "services" #E2E3F5 {
        [navigation_service] #B7BBF2
    }

    package "contracts" #E2E3F5 {
            [location_queries] #B7BBF2
            [passage_queries] #B7BBF2
    }
}

rectangle "application" #8387C4 {

    package "contract_impl" #E2E3F5 {
        [location_query_impl] #B7BBF2
        [passage_query_impl] #B7BBF2
      }

    package "use_case_impl" #E2E3F5 {
        [move_player_impl] #B7BBF2
      }

    package "dto_domain_mapping" #E2E3F5 {
             [location_mapper] #B7BBF2
             [passage_mapper] #B7BBF2
    }

}

rectangle "port" #8387C4 {

    package "dto" #E2E3F5 {
        [location_dto] #B7BBF2
        [passage_dto] #B7BBF2
      }

    package "use_case" #E2E3F5 {
        [move_player] #B7BBF2
      }

    package "repositories" #E2E3F5 {
        [location_repository] #B7BBF2
        [passage_repository] #B7BBF2
      }

    package "dto_domain_mapping" #E2E3F5 {
             [location_mapper] #B7BBF2
             [passage_mapper] #B7BBF2
    }

}


rectangle "adapter" #8387C4 {

    package "persistence" #E2E3F5 {
        [location_repository_impl_in_memory] #B7BBF2
        [passage_repository_impl_in_memory] #B7BBF2
      }

    package "web" #E2E3F5 {
        package "controller" #E2E3F5 {
                [player_controller] #B7BBF2
                [admin_controller] #B7BBF2
           }
         [server]   #B7BBF2
         [app_state] #B7BBF2
      }
}

rectangle "entry_point" #8387C4 {

    [main] #B7BBF2

}

}

' ***********************
' layout
' ***********************

' layer crosscutting to domain_pure
        [location]-[hidden]-[Errors]
        [location_queries]-[hidden]-[Errors]
        [passage_queries]-[hidden]-[Errors]


' layer domain_pure to application
        [location_query_impl]-[hidden]-[passage_queries]
        [location_query_impl]-[hidden]--[service 1]
        

' layer application to port
          [move_player]----[hidden]----[passage_mapper]
          [passage_repository]--[hidden]-[passage_mapper]


' layer port - application

          [move_player]-[hidden]-[passage_mapper]
          [passage_repository]-[hidden]-[passage_mapper]

' layer adapter

          [location_repository_impl_in_memory]-[hidden]-[location_repository]


          [main]-[hidden]-[location_repository_impl_in_memory]
          [main]-[hidden]-[passage_repository_impl_in_memory]
           [main]-[hidden]-[player_controller]

' ***********************
' implements
' ***********************

        [move_player_impl].|>[move_player] : "    implements"
        [passage_repository_impl_in_memory].|>[passage_repository] : "    implements"
        [location_repository_impl_in_memory].|>[location_repository] : "    implements"


        [passage_query_impl]...|>[passage_queries]: "    implements"
        [location_query_impl]...|>[location_queries]: "    implements"

        [player_controller] --> [move_player]: "    uses"

        [passage_mapper] -> [passage]: "    uses"
        [location_mapper] -> [location]: "    uses"

        [passage_mapper] --> [passage_dto]: "    uses"
        [location_mapper] --> [location_dto]: "    uses"


@enduml
