@startuml Whitebox_Overall_DomainComponent

!define Actor(name) actor name as "**<color:RoyalBlue>name</color>**"
!define DomainComponent(name) rectangle name as "**<color:Tomato>name</color>**"
!define NeighbouringDomain(name) rectangle name as "**<color:SeaGreen>name</color>**"
!define Database(name) database name as "**<color:Tomato>name</color>**"
!define Component(name) component name as "**<color:SlateGray>name</color>**"

skinparam ArrowColor DeepSkyBlue
skinparam ActorBorderColor DarkSlateGray
skinparam RectangleBorderColor DarkSlateGray
skinparam ComponentBorderColor DarkSlateGray
skinparam DatabaseBorderColor DarkSlateGray

  Actor(Player)
  
  DomainComponent(Frontend)
  note left: ReactJS in browser
  DomainComponent(Backend)
  note left: Rust in ActixWeb
    Database(Database)

  Component(OIDC_Authorization_Server)
  Component(MessageBroker)

  NeighbouringDomain(Game_Designer)
  NeighbouringDomain(GameCatalogue)

' Our Bounded Context

Player --> Frontend : Game interaction

Frontend --> Backend : REST
Frontend <-- Backend : Websockets

Backend <--> OIDC_Authorization_Server : OIDC Flow
Frontend <--> OIDC_Authorization_Server : OIDC Flow
Backend --> Database : Reads from/Writes to

Backend <----> MessageBroker : Publishes/Subscribes

' Other Bounded Contexts

Game_Designer <--> MessageBroker : Publishes/Subscribes
GameCatalogue <--> MessageBroker : Publishes/Subscribes


@enduml
