== Context and Scope

In the <<_abstract>> we deduced, how the complex scope of the TaleForge project and the commitment to Domain Driven Design (DDD) prompted us to divide the problem domain into subdomains. This document is dedicated to the Domain "Game Execution" that is committed to facilitate the execution of text adventure games. DDD concepts and lingo will be used to describe the relation of this domain to its context.

=== Business context

According to DDD the communication will consist of Domain Events transmitted from and to other domains.

This description will remain work in progress as our domain is the first to be explored in detail.

At this point, the domain events are mocked since the neighbouring domains are not yet implemented.

|===
| Neighbouring Subdomai\ndd | Domain Event | Data Content | Description

| Game Design
| Release Game
| Game layout
| An adventure that has previously been designed is transmitted to our backend as one of the games it can facilitate. The release process involves creating a snapshot that will remain stable enough to allow game execution independently from potential further changes to the design.

| Game Catalogue
| Start Game Execution
| List of Players
| An adventurer or a group of adventurers start a game, so they can play. This will likely be initiate from some sort of catalogue, where potential players can explore possible games. For multiplayer games some kind of mechanism has to be developed to define a group of users, that play one adventure together.

|===

The interaction with the player(s) during game execution is not listed here since this happens within the domain "Game Execution".

=== Technical Context

|===
| Technical Component | Interface | System (likely) | Description

| OIDC Authorization Server
| HTTP(S) / OAUTH2
| Keycloak
| tbc

| Database
| ODBC (?)
| PostgreSQL
| tbc

| Message Broker
| ?
| tbd
| DDD encourages asynchronous communication between the bounded contexts - this could in a first step also be modelled through a conventional data base

| Browser
| HTTP(S)
| tbd
| tbc

| Docker Runtime
| OCI
| tbd
| tbc

|===

The interaction with the player(s) during game execution is not listed here since this happens within the domain.