== Context and Scope

In the section <<Scope of the Document>> we explained that the complex vision of the TaleForge project requires a building-block-approach to the overall architecture to manage the complexity.

This document describes the backend of the core domain dedicated to the facilitation of an adventure game.

As the project is dedicated to Domain Driven Design (DDD), the associated language and concepts will be used to describe the relation of the building block to its context.

=== Business context

This description will remain a bit vague as the context is not yet fully explored. In due time there will be a document describing the whole system.

According to DDD the communication will consist of Domain Events transmitted from and to other domains.

|===
| Neighbouring Subdomain | Domain Event | Data Content | Description

| unknown - mocked at this time
| Release Game
| Game layout
| An adventure that has previously been designed is transmitted to our backend as one of the games it can facilitate

| unknown - mocked at this time
| Start Game Execution
| List of players
| An adventurer or a group of adventurers start a game, so they can play

|===

The interaction with the player(s) during game execution is not listed here since this happens within the domain.

=== Technical Context

|===
| Technical Environment | Interface | System (likely) | Description

| OIDC Authorization Server
| HTTP(S) / OAUTH2
| Keycloak
| tbc

| Database
| ODBC (?)
| PostgreSQL
| tbc

| Message Broker
| ?
| tbd
| tbc

| Browser
| HTTP(S)
| tbd
| tbc

|===

The interaction with the player(s) during game execution is not listed here since this happens within the domain.

* Databases (probably relational)
* Authorization server ()
