== Context and Scope

In the section <<Scope of the Document>> we explained that the complex vision of the TaleForge project requires a building-block-approach to the overall architecture to manage the complexity.

This document describes the backend of the core domain dedicated to the facilitation of an adventure game.

As the project is dedicated to Domain Driven Design (DDD), the associated language and concepts will be used to describe the relation of the building block to its context.

=== Business context

According to DDD the communication will consist of Domain Events transmitted from and to other domains.

This description will remain work in progress as our domain is the first to be explored in detail.

At this point, the domain events are mocked since the neighbouring domains are not yet implemented.

|===
| Neighbouring Subdomain | Domain Event | Data Content | Description

| Game Design
| Release Game
| Game layout
| An adventure that has previously been designed is transmitted to our backend as one of the games it can facilitate. The release process involves creating a snapshot that will remain stable enough to allow game execution independently from potential further changes to the design.

| Game Catalogue
| Start Game Execution
| List of Players
| An adventurer or a group of adventurers start a game, so they can play. This will likely be initiate from some sort of catalogue, where potential players can explore possible games. For multiplayer games some kind of mechanism has to be developed to define a group of users, that play one adventure together.

|===

The interaction with the player(s) during game execution is not listed here since this happens within the domain "Game Execution".

=== Technical Context

|===
| Technical Component | Interface | System (likely) | Description

| OIDC Authorization Server
| HTTP(S) / OAUTH2
| Keycloak
| tbc

| Database
| ODBC (?)
| PostgreSQL
| tbc

| Message Broker
| ?
| tbd
| tbc

| Browser
| HTTP(S)
| tbd
| tbc

| Docker Runtime
| OCI
| tbd
| tbc

|===

The interaction with the player(s) during game execution is not listed here since this happens within the domain.

