[package]
name = "entry_point"
version = "0.1.0"
edition = "2021"


[dependencies]
port = { path = "../port" }
domain = { path = "../domain" }
adapter = { path = "../adapter" }
application = { path = "../application" }

actix-web = "4.0.0"
serde = { version = "1.0", features = ["derive"] }