[package]
name = "port"
version = "0.1.0"
edition = "2021"

[dependencies]
domain_pure = { path = "../domain_pure" }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
assert_cmd = "1.0"
predicates = "1.0"
