openapi: 3.0.0
info:
  title: Adventure Game API
  version: 1.0.0
servers:
  - url: 'http://localhost:8000'
paths:
  /players/{playerId}/move:
    post:
      summary: Move player in a given direction
      parameters:
        - in: path
          name: playerId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                direction:
                  type: string
                gameId:
                  type: string
      responses:
        200:
          description: Player moved successfully
  /players/{playerId}/rooms/current:
    get:
      summary: Get current room description
      parameters:
        - in: path
          name: playerId
          required: true
          schema:
            type: string
      responses:
        200:
          description: Current room description
          content:
            application/json:
              schema:
                type: object
                properties:
                  description:
                    type: string
                  imageUrl:
                    type: string
  /players/{playerId}/rooms/current/directions:
    get:
      summary: Get possible directions from the current room
      parameters:
        - in: path
          name: playerId
          required: true
          schema:
            type: string
      responses:
        200:
          description: Possible directions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /rooms/{roomId}/image:
    get:
      summary: Get room image
      parameters:
        - in: path
          name: roomId
          required: true
          schema:
            type: string
      responses:
        200:
          description: Image file
          content:
            image/png:
              schema:
                type: string
                format: binary
