openapi: 3.0.0
info:
  title: Game API
  version: "1.0.0"
paths:
  /move/player:
    post:
      summary: Move player in a given direction
      operationId: movePlayer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - player_id
                - bout_id
                - direction
              properties:
                player_id:
                  type: integer
                  format: int64
                  description: The unique identifier for a player.
                bout_id:
                  type: integer
                  format: int64
                  description: The unique identifier for a bout.
                direction:
                  type: string
                  description: The direction in which the player wants to move.
      responses:
        '200':
          description: Player moved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovePlayerResponse'
        '400':
          description: Invalid input
        '404':
          description: Player or bout not found

components:
  schemas:
    MovePlayerResponse:
      type: object
      properties:
        player_location:
          type: integer
          format: int64
        narration:
          type: string
