openapi: 3.0.0
info:
  title: Game API
  version: "1.0.0"
paths:
  /player/move:
    post:
      summary: Move player in a given direction
      operationId: movePlayer
      tags:
        - Player
      requestBody:
        description: Request parameters needed for moving a player
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovePlayerRequest'
      responses:
        '200':
          description: Player moved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovePlayerResponse'
        '400':
          description: Invalid input, such as validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Player or bout not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    MovePlayerRequest:
      type: object
      required:
        - playerId
        - boutId
        - direction
      properties:
        playerId:
          type: integer
          format: int64
        boutId:
          type: integer
          format: int64
        direction:
          type: string
    MovePlayerResponse:
      type: object
      properties:
        newLocation:
          type: integer
          format: int64
        narration:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: 'unexpected_error'
        message:
          type: string
          example: 'An unexpected error occurred.'
