openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
paths:
  /move/player:
    post:
      summary: Move a player in a given direction
      operationId: movePlayer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                bout_id:
                  type: integer
                  format: int64
                  description: The unique identifier for a bout
                player_id:
                  type: integer
                  format: int64
                  description: The unique identifier for a player
                direction:
                  type: string
                  description: The direction in which the player wants to move
      responses:
        '200':
          description: Player moved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  player_location:
                    type: integer
                    format: int64
                  narration:
                    type: string
        '400':
          description: Invalid input
        '404':
          description: Player or bout not found
