openapi: 3.0.0
info:
  title: Adventure Game API
  version: 1.0.0
servers:
  - url: 'http://localhost:8000'
paths:
  /move/player:
    post:
      summary: Move player in a given direction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - playerId
                - boutId
                - direction
              properties:
                playerId:
                  type: string
                  description: Unique identifier of the player character
                boutId:
                  type: string
                  description: Unique identifier of the bout or game session
                direction:
                  type: string
                  description: The direction in which the player wants to move
      responses:
        200:
          description: Player moved successfully
        400:
          description: Invalid input
        404:
          description: Player or bout not found
